version: '3'
services:
  #Postgres
    postgres:
       image: 'postgres:latest'
       environment:
         - POSTGRES_PASSWORD=postgres_password
         - POSTGRES_DB=simple-blog-api
  #Simple_api
    simple-blog-api:
      depends_on:
        - postgres
      #restart: always
      image: fshwetha/simple-blog-api
      build: .
      ports:
          - "3000:3000"
      environment:
         - POSTGRES_HOST=postgres
         - POSTGRES_PORT=5432
         - POSTGRES_USERNAME=postgres
         - POSTGRES_PASSWORD=postgres_password
         - POSTGRES_DB=simple-blog-api